### ISSUE TITLE
any readme or screenshot?

### ISSUE THREAD

**Issue by xycloud** [Kikketer/generic-feedback-plugin#1]
any readme or screenshot?

**Comment by Kikketer** [comment]
This plugin was built to expose a bug in the @elastic/plugin-helpers project.  Feel free to use it as an example but I recommend starting with the https://github.com/elastic/generator-kibana-plugin.

This is really a ripped down version of what that creates and isn't maintained.  I may revisit this if I need to use it as a test dummy again.

For details of where this was used, see: https://github.com/elastic/kibana-plugin-helpers/issues/18
